version: "8"
services:
  app:
    build:
      context: .djangomysql
      dockerfile: Dockerfiles
    entrypoint: ["./wait.sh"]
    depends_on: #links:
      - db-1
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: root0
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
